# Jobs Dataset Cleaning Project

This notebook demonstrates how to clean and preprocess a raw, uncleaned jobs dataset. It involves handling missing data, correcting data types, standardizing job titles, and other relevant data cleaning tasks.

# Skills Highlight:

**Python**: Data manipulation using pandas.

**Data Cleaning**: Handling missing values, correcting inconsistencies, and preparing the dataset for analysis.

**Exploratory Data Analysis**: Initial exploration to understand the structure and quality of the dataset.

# Objective:

Clean and preprocess the uncleaned jobs dataset.

Address missing values, inconsistencies, and duplicates.

Prepare the dataset for further analysis or modeling.

# Data Loading and Initial Inspection

We begin by loading the raw jobs dataset and inspecting it for any immediate issues, such as missing values, duplicate entries, or inconsistent formatting.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Uncleaned_DS_jobs.csv to Uncleaned_DS_jobs (1).csv

In [ ]:
df = pd.read_csv('/content/Uncleaned_DS_jobs.csv')

In [ ]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

# Data Cleaning

In this section, we will clean and preprocess the raw jobs dataset to ensure it is suitable for further analysis or modeling. Data cleaning is a critical step because real-world datasets often contain errors, inconsistencies, or missing values that can affect the accuracy and reliability of analysis.

The key cleaning tasks we'll perform include:

**Handling Missing Data**: We will check for any missing values and decide whether to impute, fill, or drop these entries based on the nature of the data.
**Removing Duplicates**: Duplicate rows can skew analysis results, so we will identify and remove any redundant entries.

**Correcting Data Types**: Ensuring that numeric, categorical, and date fields are correctly typed is essential for smooth data manipulation.

**Standardizing Formats**: We will ensure that categorical data (such as job titles) is standardized to prevent inconsistencies during analysis.

In [ ]:
df = df.drop_duplicates()

After executing the drop_duplicates() function, we have removed any duplicate rows from the dataset. This step is critical in ensuring data integrity, as duplicate entries can distort analytical results, especially in business analytics and financial forecasting.

In [ ]:
df.dtypes

index                  int64
Job Title             object
Salary Estimate       object
Job Description       object
Rating               float64
Company Name          object
Location              object
Headquarters          object
Size                  object
Founded                int64
Type of ownership     object
Industry              object
Sector                object
Revenue               object
Competitors           object
dtype: object

In [ ]:
df.replace('-1', pd.NA, inplace=True)

In this step, we replaced all instances of -1 with NA, which represents missing values in our dataset. The value -1 likely indicates missing or unknown data, and it is common in datasets to use placeholder values like -1 to represent missing information. Replacing -1 with a proper NA value helps in several ways such as Improveing Data Consistency and Enhances Analytical Accuracy.

In [ ]:
print(df['Founded'])

0      1993
1      1968
2      1981
3      2000
4      1998
       ...
667    1989
668    <na>
669    <na>
670    <na>
671    1976
Name: Founded, Length: 672, dtype: object

In [ ]:
print(df['Rating'])

0       3.1
1       4.2
2       3.8
3       3.5
4       2.9
       ...
667     3.6
668    <na>
669    <na>
670     5.0
671     2.7
Name: Rating, Length: 672, dtype: object

In [ ]:
text_columns = df.select_dtypes(include=['object']).columns

In [ ]:
df[text_columns] = df[text_columns].astype(str).apply(lambda x: x.str.lower())

In this step, we converted all text columns in the dataset to lowercase. By applying this transformation, we standardize the textual data, ensuring uniformity in the way information is stored and processed.

In [ ]:
df[['headquarter_city', 'headquarter_state']] = df.Headquarters.str.split(expand=True,
                       pat=', ')

In this step, we split the values in the Headquarters column into two separate columns: headquarter_city and headquarter_state. The original Headquarters column contained both the city and state information in a single field, and by splitting the data, we make it easier to work with location-specific information.

In [ ]:
print(df['Competitors'])

0                emblemhealth, unitedhealth group, aetna
1                                                   <na>
2                                                   <na>
3      mks instruments, pfeiffer vacuum, agilent tech...
4                   commerce signals, cardlytics, yodlee
                             ...
667                                                 <na>
668                                                 <na>
669                                                 <na>
670                                                 <na>
671                                                 <na>
Name: Competitors, Length: 672, dtype: object

In [ ]:
df.drop(['Competitors'], axis=1, inplace = True)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,headquarter_city,headquarter_state
0,0,sr data scientist,$137k-$171k (glassdoor est.),description\n\nthe senior data scientist is re...,3.1,healthfirst\n3.1,"new york, ny","new york, ny",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,unknown / non-applicable,new york,ny
1,1,data scientist,$137k-$171k (glassdoor est.),"secure our nation, ignite your future\n\njoin ...",4.2,mantech\n4.2,"chantilly, va","herndon, va",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),herndon,va
2,2,data scientist,$137k-$171k (glassdoor est.),overview\n\n\nanalysis group is one of the lar...,3.8,analysis group\n3.8,"boston, ma","boston, ma",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),boston,ma
3,3,data scientist,$137k-$171k (glassdoor est.),job description:\n\ndo you have a passion for ...,3.5,inficon\n3.5,"newton, ma","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),bad ragaz,switzerland
4,4,data scientist,$137k-$171k (glassdoor est.),data scientist\naffinity solutions / marketing...,2.9,affinity solutions\n2.9,"new york, ny","new york, ny",51 to 200 employees,1998,company - private,advertising & marketing,business services,unknown / non-applicable,new york,ny

In this step, we dropped the "Competitors" column from the dataset due to it having Irrelevant or Redundant Data

In [ ]:
df['Job Title'].value_counts()

Job Title
data scientist                                            337
data engineer                                              26
senior data scientist                                      19
machine learning engineer                                  16
data analyst                                               12
                                                         ...
data science instructor                                     1
business data analyst                                       1
purification scientist                                      1
data engineer, enterprise analytics                         1
ai/ml - machine learning scientist, siri understanding      1
Name: count, Length: 172, dtype: int64

In [ ]:
df['Job Title'].unique()

array(['sr data scientist', 'data scientist',
       'data scientist / machine learning expert',
       'staff data scientist - analytics',
       'data scientist - statistics, early career', 'data modeler',
       'experienced data scientist', 'data scientist - contract',
       'data analyst ii', 'medical lab scientist',
       'data scientist/machine learning', 'human factors scientist',
       'business intelligence analyst i- data insights',
       'data scientist - risk', 'data scientist-human resources',
       'senior research statistician- data scientist', 'data engineer',
       'associate data scientist', 'business intelligence analyst',
       'senior analyst/data scientist', 'data analyst',
       'machine learning engineer', 'data analyst i',
       'scientist - molecular biology',
       'computational scientist, machine learning',
       'senior data scientist', 'jr. data engineer',
       'e-commerce data analyst', 'data analytics engineer',
       'product data scientist - ads data science',
       'data scientist - intermediate', 'global data analyst',
       'data & machine learning scientist',
       'data scientist - machine learning', 'data engineer (remote)',
       'data scientist, applied machine learning - bay area',
       'principal data scientist', 'business data analyst',
       'purification scientist', 'data engineer, enterprise analytics',
       'data scientist 3 (718)', 'real world science, data scientist',
       'data scientist - image and video analytics',
       'data science manager, payment acceptance - usa',
       'data scientist / applied mathematician',
       'patient safety- associate data scientist',
       '(sr.) data scientist -', 'data scientist, kinship - nyc/portland',
       'applied technology researcher / data scientist',
       'health data scientist - biomedical/biostats',
       'staff data scientist', 'sr data engineer (sr bi developer)',
       'lead data scientist', 'rfp data analyst',
       'data scientist (ts/sci)', 'software engineer - data science',
       'data analyst/engineer', 'ngs scientist', 'senior data engineer',
       'sr. ml/data scientist - ai/nlp/chatbot',
       'data integration and modeling engineer',
       'tableau data engineer 20-0117', 'ai data scientist',
       'research scientist patient preferences (remote)',
       'scientist - biomarker and flow cytometry', 'analytics manager',
       'staff scientist- upstream pd',
       'sr scientist - extractables & leachables',
       'elisa research scientist (cv-15)', 'say business data analyst',
       'geospatial data scientist', 'computational scientist',
       'senior data analyst', 'sr data analyst',
       'machine learning scientist - bay area, ca',
       'senior data scientist - algorithms',
       'senior data & machine learning scientist',
       'research scientist - patient-centered research (remote)',
       'jr. business data analyst (position added 6/12/2020)',
       'sr. data scientist ii',
       'production engineer - statistics/data analysis',
       'statistical scientist', 'computational behavioral scientist',
       'principal data scientist - machine learning',
       'principal machine learning scientist',
       'senior data scientist - r&d oncology',
       'health plan data analyst, sr',
       'principal scientist/associate director, quality control and analytical technologies',
       'analytics - business assurance data analyst',
       'senior data scientist – image analytics, novartis ai innovation lab',
       'data science instructor', 'senior business intelligence analyst',
       'in-line inspection data analyst',
       'data scientist - ts/sci fsp or ci required',
       'data scientist - ts/sci required',
       'data science software engineer',
       'engineer - computer scientist - research computer scientist - signal processing - san antonio or',
       'ai ops data scientist', 'intelligence data analyst, senior',
       'analytics manager - data mart',
       'data modeler (analytical systems)',
       'senior machine learning scientist - bay area, ca',
       'report writer-data analyst', 'staff data scientist - pricing',
       'equity data insights analyst - quantitative analyst',
       'operations data analyst', 'software data engineer',
       'real world evidence (rwe) scientist', 'computer scientist 1',
       'environmental data science', 'staff bi and data engineer',
       'data scientist - statistics, mid-career',
       'director of data science',
       'data engineer, digital & comp pathology',
       'manager / lead, data science & analytics',
       'diversity and inclusion data analyst',
       'data scientist machine learning', 'chief scientist',
       'development scientist, voltaren',
       'principal data & analytics platform engineer',
       'machine learning engineer/scientist',
       'data analyst - unilever prestige', 'vp, data science',
       'data engineer - kafka', 'decision scientist',
       'data science all star program - data engineer track',
       'scientist - machine learning', 'sr. data scientist',
       'applied ai scientist / engineer',
       'data engineer (analytics, sql, python, aws)',
       'senior data analyst - finance & platform analytics',
       'market research data scientist',
       'it partner digital health technology and data science',
       'software engineer (data scientist, c,c++,linux,unix) - sisw - mg',
       'senior clinical data scientist programmer',
       'computer vision / deep learning scientist',
       'data solutions engineer - data modeler',
       'data scientist (ts/sci w/ poly)',
       'weapons and sensors engineer/scientist',
       'applied computer scientist', 'cloud data engineer (azure)',
       'lead certified clinical laboratory scientist - saturday - tuesday, 8:00pm - 6:30am shift',
       'sr. data analyst',
       'senior scientist - toxicologist - product integrity (stewardship)',
       'senior machine learning engineer',
       'data scientist- industrial discrete sector industry',
       'senior principal data scientist (python/r)',
       'data scientist(s)/machine learning engineer',
       'scientist / group lead, cancer biology',
       'manager, field application scientist, southeast',
       'computer scientist - engineer - research computer scientist - signal processing',
       'machine learning scientist / engineer', 'data science analyst',
       'computer scientist - engineer - research computer scientist - transportation technology',
       'software engineer - machine learning & data science (applied intelligence services team)',
       'clinical data analyst', 'data scientist technical specialist',
       'data science manager', 'big data engineer', 'data architect',
       'aviation ai/ml data scientist', 'machine learning engineer, sr.',
       'information systems engineering specialist (engineering scientist)',
       'scientist/research associate-metabolic engineering',
       'vice president, biometrics and clinical data management',
       'enterprise data analyst (enterprise portfolio management office)',
       'lead data scientist – network analysis and control',
       'sr. research associate/ scientist, ngs prep & molecular genomics',
       'developer iii - data science',
       'hydrogen/tritium materials scientist (experienced)',
       'data scientist/data analytics practitioner',
       'ai/ml - machine learning scientist, siri understanding'],
      dtype=object)

In [ ]:
def job_title_cleaning(title):
  if 'data scientist' in title.lower():
    return 'Data Scientist'
  elif ' data engineer' in title.lower():
    return 'Data Engineer'
  elif 'analyst' in title.lower():
    return 'Analyst'
  elif 'manager' in title.lower():
    return 'Manager'
  elif 'director' in title.lower():
    return 'Director'
  else:
    return 'Other'

In this step, we created a function called job_title_cleaning to standardize job titles in the dataset. This function examines each job title and assigns it to one of the predefined categories: Data Scientist, Data Engineer, Analyst, Manager, Director, or Other. The function ensures that variations in job titles are grouped under a consistent category for more meaningful analysis.

In [ ]:
df['Job Title Cleaned'] = df['Job Title'].apply(job_title_cleaning)
df['Job Title Cleaned'].value_counts()

Job Title Cleaned
Data Scientist    455
Other             138
Analyst            55
Data Engineer      14
Manager             7
Director            3
Name: count, dtype: int64

In [ ]:
def level_cleaning(title):
  if 'sr' in title.lower() or 'senior' in title.lower() or 'lead' in title.lower() or 'principal' in title.lower():
    return 'Senior'
  elif 'jr' in title.lower() or 'jr.' in title.lower():
    return 'Junior'
  else:
    return ' Other'

This function, level_cleaning, standardizes job titles based on their seniority levels. It categorizes roles as either Senior, Junior, or Other by examining keywords in the job title such as "Sr", "Senior", "Lead", or "Principal" for senior roles, and "Jr" or "Junior" for junior roles. Any title that doesn't fit these categories is classified as Other.

In [ ]:
df['Job Level'] = df['Job Title'].apply(level_cleaning)
df['Job Level'].value_counts()

Job Level
 Other    576
Senior     94
Junior      2
Name: count, dtype: int64

In [ ]:
df.drop(['Job Title'], axis = 1, inplace = True)
df.head()

,index,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,headquarter_city,headquarter_state,Job Title Cleaned,Job Level
0,0,$137k-$171k (glassdoor est.),description\n\nthe senior data scientist is re...,3.1,healthfirst\n3.1,"new york, ny","new york, ny",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,unknown / non-applicable,new york,ny,Data Scientist,Senior
1,1,$137k-$171k (glassdoor est.),"secure our nation, ignite your future\n\njoin ...",4.2,mantech\n4.2,"chantilly, va","herndon, va",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),herndon,va,Data Scientist,Other
2,2,$137k-$171k (glassdoor est.),overview\n\n\nanalysis group is one of the lar...,3.8,analysis group\n3.8,"boston, ma","boston, ma",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),boston,ma,Data Scientist,Other
3,3,$137k-$171k (glassdoor est.),job description:\n\ndo you have a passion for ...,3.5,inficon\n3.5,"newton, ma","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),bad ragaz,switzerland,Data Scientist,Other
4,4,$137k-$171k (glassdoor est.),data scientist\naffinity solutions / marketing...,2.9,affinity solutions\n2.9,"new york, ny","new york, ny",51 to 200 employees,1998,company - private,advertising & marketing,business services,unknown / non-applicable,new york,ny,Data Scientist,Other

In this step, we removed the Job Title column from the dataset because we have a new column named "Job Title Cleaned".

In [ ]:
df['Salary Estimate'] = df['Salary Estimate'].str.replace(r"\(glassdoor est.\)", "", regex=True)

In this step, we removed the "(glassdoor est.)" text from the Salary Estimate column using the str.replace() method. This transformation cleans up the salary data by removing unnecessary information, leaving only the numeric salary estimate.

In [ ]:
df.head()

,index,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,headquarter_city,headquarter_state,Job Title Cleaned,Job Level
0,0,$137k-$171k,description\n\nthe senior data scientist is re...,3.1,healthfirst\n3.1,"new york, ny","new york, ny",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,unknown / non-applicable,new york,ny,Data Scientist,Senior
1,1,$137k-$171k,"secure our nation, ignite your future\n\njoin ...",4.2,mantech\n4.2,"chantilly, va","herndon, va",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),herndon,va,Data Scientist,Other
2,2,$137k-$171k,overview\n\n\nanalysis group is one of the lar...,3.8,analysis group\n3.8,"boston, ma","boston, ma",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),boston,ma,Data Scientist,Other
3,3,$137k-$171k,job description:\n\ndo you have a passion for ...,3.5,inficon\n3.5,"newton, ma","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),bad ragaz,switzerland,Data Scientist,Other
4,4,$137k-$171k,data scientist\naffinity solutions / marketing...,2.9,affinity solutions\n2.9,"new york, ny","new york, ny",51 to 200 employees,1998,company - private,advertising & marketing,business services,unknown / non-applicable,new york,ny,Data Scientist,Other

In [ ]:
df['Company Name'] = df['Company Name'].apply(lambda x: x.split('\n')[0])
df['Company Name']

0               healthfirst
1                   mantech
2            analysis group
3                   inficon
4        affinity solutions
               ...
667                tranzact
668                    jkgt
669              accesshope
670    chateck incorporated
671           1-800-flowers
Name: Company Name, Length: 672, dtype: object

In [ ]:
# Check if the "Headquarters" column exists before attempting to drop it.
if 'Headquarters' in df.columns:
    df.drop(['Headquarters'], axis=1, inplace=True)
else:
    print("Column 'Headquarters' not found in the DataFrame.")

In this step, we perform a conditional check to determine if the original Headquarters column exists in the dataset before attempting to drop it. If the column is present, it is removed; otherwise, a message is printed indicating that the column was not found.

In [ ]:
# prompt: how do i see how many different types of data is in my Job Title Cleaned Row

df['Job Title Cleaned'].value_counts()

Job Title Cleaned
Data Scientist    455
Other             138
Analyst            55
Data Engineer      14
Manager             7
Director            3
Name: count, dtype: int64

In [ ]:
df['Job Description'] = df['Job Description'].str.replace('\n', '')

In this step, we removed all newline characters (\n) from the Job Description column. Newline characters often appear in textual data when descriptions span multiple lines or include formatted text. While useful for readability in some contexts, these characters are unnecessary for structured data analysis and can cause issues during processing.

In [ ]:
df.head( )

,index,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,headquarter_city,headquarter_state,Job Title Cleaned,Job Level
0,0,$137k-$171k,descriptionthe senior data scientist is respon...,3.1,healthfirst,"new york, ny",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,unknown / non-applicable,new york,ny,Data Scientist,Senior
1,1,$137k-$171k,"secure our nation, ignite your futurejoin the ...",4.2,mantech,"chantilly, va",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),herndon,va,Data Scientist,Other
2,2,$137k-$171k,overviewanalysis group is one of the largest i...,3.8,analysis group,"boston, ma",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),boston,ma,Data Scientist,Other
3,3,$137k-$171k,job description:do you have a passion for data...,3.5,inficon,"newton, ma",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),bad ragaz,switzerland,Data Scientist,Other
4,4,$137k-$171k,data scientistaffinity solutions / marketing c...,2.9,affinity solutions,"new york, ny",51 to 200 employees,1998,company - private,advertising & marketing,business services,unknown / non-applicable,new york,ny,Data Scientist,Other

# Conclusion

In this notebook, we successfully cleaned and processed the raw jobs dataset. The data is now free of duplicates, missing values have been handled appropriately, and formatting has been standardized. The dataset is now ready for further analysis or modeling.